### ISSUE TITLE
cp: cannot create regular file 'rootfs/usr/bin': No such file or directory

### ISSUE THREAD

**Issue by doniks** [JBBgameich/halium-install#10]
I get this error message. I'm using this repo for the first time, so maybe I am doing something wrong

A cursory scan of the script indicates that a folder rootfs is created, subfolders usr and bin are not created but later assumed to exist. I might be wrong

$ ./halium-install ../halium-rootfs/ubports-2018-01-03.tar.gz ../halium-out-system.img 
Debug: Chosen rootfs is ../halium-rootfs/ubports-2018-01-03.tar.gz
Debug: Chosen android image is ../halium-out-system.img
Debug: Chosen release is none

I: Writing rootfs into mountable image
I: Writing android image into mountable image
I: Setting up passwd for root user
cp: cannot create regular file 'rootfs/usr/bin': No such file or directory
chroot: failed to run command ‘passwd’: No such file or directory
rm: cannot remove 'rootfs/usr/bin/qemu-arm-static': No such file or directory
I: Running post installation tasks
I: Unmounting images
I: Shrinking images
e2fsck 1.43.5 (04-Aug-2017)
resize2fs 1.43.5 (04-Aug-2017)
Resizing the filesystem on system.img to 35294 (4k) blocks.
Begin pass 2 (max = 17160)
Relocating blocks             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Begin pass 3 (max = 7)
Scanning inode table          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
The filesystem on system.img is now 35294 (4k) blocks long.

I: Pushing rootfs and android image to /data via ADB
system.img: 1 file pushed. 3.9 MB/s (144564224 bytes in 35.196s)
[ 45%] /data/rootfs.img

**Comment by JBBgameich** [comment]
I'll try to reproduce the problem. Maybe the UBports image is different from the reference rootfs in some way that breaks extracting. All subfolders like usr/bin should be created automatically when extracting the tarball.

**Comment by jbruechert** [comment]
looks like quemu-arm-static is not in your $PATH, I wonder why the script didn't complain about that

**Comment by doniks** [comment]
Right now I have:

which qemu-arm-static 
/usr/bin/qemu-arm-static

However, when I ran the script first, I did not have it installed, so I did the apt install ...stuff... then retried and got the error, so maybe something left over from the first attempt?

**Comment by doniks** [comment]
I think I was using the wrong kind of ubports image. it had everything in a /system/ subdirectory, which I think is not halium compatible
