### ISSUE TITLE
Set different rootfs.img sizes for different targets

### ISSUE THREAD

**Issue by vanyasem** [JBBgameich/halium-install#15]
2Gb is enough for Plasma Mobile, but UBports requires >2.5Gb
Reference Halium rootfs needs less than a gigabyte

I think that's a good idea to dynamically set the size based on the "target" selected
Currently the script defaults to 2Gb and leaves UBports in a broken state because of that

**Comment by jbruechert** [comment]
I agree there. Can we maybe find out the size of the content of the tar and create a image with the correct size somehow? I'd like to avoid hardcoding the sizes again

**Comment by Tofee** [comment]
For LuneOS we simply unpack the rootfs archive in the /userdata/halilum-rootfs folder; therefore we don't have this rootfs.img size issue, which seems artificial (i.e. you'll never have it on a real device, where you use the system partition).
Though I understand the topic of this issue isn't to question the use of root.img, what is the advantage of going through a root.img file?

**Comment by jbruechert** [comment]
I added this feature in 2937648a99174598e1546623f4480cfc1573ed35.

**Comment by jbruechert** [comment]
@Tofee I agree that it makes sense to discuss the use of ext4 images again, but let's better do that in the Halium IRC / Telegram channel, and not on this GitHub issue. Is there any use / need for a luneOS install mode in this script by the way?

**Comment by Tofee** [comment]
No we don't have any use for halium-install at the moment; our whole rootfs is built by our toolchain, producing a sideload-able zip file.
