### ISSUE TITLE
standalone gives error

### ISSUE THREAD

**Issue by doniks** [JBBgameich/halium-install#22]
wget  https://github.com/JBBgameich/halium-install/releases/download/continuous/halium-install-standalone.sh
chmod +x halium-install-standalone.sh
./halium-install-standalone.sh: line 15: usage: command not found

I think the functions need to be on top of the script

**Comment by jbruechert** [comment]
Ok I'll look into fixing it when I'm at home. Thanks for reporting!

**Comment by doniks** [comment]
Old issue and I haven't used standalone since forever and I haven't heard anybody else flag this, probably a useless issue by now. Closing
