### ISSUE TITLE
Unable to install aarch64 rootfs

### ISSUE THREAD

**Issue by vanyasem** [JBBgameich/halium-install#24]
**Altoria Xu | 每天九点准时前往图书馆**, [24.06.18 18:50]

> Hello everyone, I'm porting Ubports to my Oneplus 5T. When I use the command "halium-install-standalone", it says "chroot: /bin/bash not found". Is there a way I can install the /bin/bash into the image? thanks.

**Altoria Xu | 每天九点准时前往图书馆**, [24.06.18 18:59]

> `./halium-install-standalone.sh ubports-touch.rootfs-xenial-arm64.tar.gz system.img ut`

**Ivan Semkin**, [24.06.18 19:10]

> JBB's script copies the arm qemu executable

**Ivan Semkin**, [24.06.18 19:10]

> when the rootfs is aarch64

**JBB(gameich)**, [24.06.18 19:11]

> Yes, this should be fixed. Do you have an idea how to detect the rootfs architecture without being able to run `uname -m` inside?

**Bhushan Shah**, [24.06.18 19:13]
_[In reply to JBB(gameich)]_

> run the file command against the libc.so file in rootfs and check that

**Comment by vanyasem** [comment]
Sorry was too lazy to form a proper issue, decided to just copy the messages from telegram

**Comment by vanyasem** [comment]
Workaround for users: `sed -i s/qemu-arm-static/qemu-aarch64-static/g functions/distributions.sh`

Btw `qemu-aarch64-static` might work with armv7 rootfs also. _Theoretically~~_

**Comment by jbruechert** [comment]
This seems to work quite well to detect the architecture: `readelf -h $BINARY | grep Machine | sed -e 's/^.*Machine: //' | xargs`

**Comment by jbruechert** [comment]
I pushed an untested patch to the [multiarch](https://github.com/JBBgameich/halium-install/tree/multiarch) branch. If someone can confirm it works with an aarch64 device, I would merge it into master.

**Comment by abhishek-mudgal** [comment]
confirmed, it is working.

**Comment by vanyasem** [comment]
Abhishek, [04.07.18 12:47]
but i still in favour of user fed cpu arch as an argument for script

**Comment by vanyasem** [comment]
i don't personally want to specify arch as an argument, i like the current solution. but it's nice to gather all opinions together

**Comment by jbruechert** [comment]
This should now be fixed in 051597650f1b720fde9776f55b5b83b3236ef56a.
If there are any problems with the current solution, feel free to reopen the issue.
