### ISSUE TITLE
Passwd error

### ISSUE THREAD

**Issue by IXgnas** [JBBgameich/halium-install#26]
The script does not give the chance to set the password, then starts spamming the following error:
`chroot: failed to run command ‘passwd’: Exec format error
Failed, please try again
`

**Comment by jbruechert** [comment]
The script requires a working installation of qemu-user-static to be able to set the password in the target rootfs.

**Comment by jbruechert** [comment]
In case you can't install it, you can still leave out the "halium" at the end of the command. Then the password is not set up and therefore no error should appear.

**Comment by jbruechert** [comment]
I'm closing this now. If the problem persists, feel free to reopen this issue.
