### ISSUE TITLE
AppImage is missing required binaries

### ISSUE THREAD

**Issue by probonopd** [JBBgameich/halium-install#6]
The AppImage does not bundle all required binaries:

![](https://github.com/AppImage/appimage.github.io/blob/28cc9e59d67338db2ad1e5d4398892dcc4e087b7/database/halium-install/screenshot.png?raw=true)

Since an AppImage should have no dependencies except what is in the default installation of the target systems, these binaries should be bundled inside the AppImage. I think `sudo` can be assumed to come with the base system but the others cannot.

Reference:
https://github.com/AppImage/appimage.github.io/pull/226

**Comment by jbruechert** [comment]
I'm not sure if this AppImage should be included into the AppImageHub, but thanks for the report anyway. I can't really reproduce it, but as the dependency tester runs as root already, sudo already has to be installed for it to run which means it can be removed from the test.

**Comment by probonopd** [comment]
Yes, I agree about `sudo`, but the other executables mentioned in the screenshot should best be bundled inside the AppImage. Especially since some `qemu-*` executables are, but seemingly not `qemu-user-static`:

```
usr/bin/qemu-unicore32-static
usr/bin/qemu-system-arm
usr/bin/qemu-system-aarch64
usr/bin/qemu-or32-static
usr/bin/qemu-nbd
usr/bin/qemu-io
usr/bin/qemu-img
usr/bin/qemu-armeb-static
usr/bin/qemu-arm-static
usr/bin/qemu-aarch64-static
```

> I'm not sure if this AppImage should be included into the AppImageHub

If you don't want to have it included, let me know and I'll remove it. But I think this is a great project that should get some more exposure ;-)

**Comment by jbruechert** [comment]
I don't think qemu-user-static is a binary, it's in the list of package names for Ubuntu / Debian

This scripts here are still unofficial, that's the only reason why I'm not sure if it should be included.

**Comment by probonopd** [comment]
> I don't think qemu-user-static is a binary, it's in the list of package names for Ubuntu / Debian

Ah, I understand. Thanks for the clarification.

**Comment by jbruechert** [comment]
I removed the sudo dependency now, can you try again?
